num=int(input("Enter no of elements:"))
list=[]
for i in range(0,num):
    el=input()
    list.append(el)
print("list:",list)
list.reverse()
print(list)
list.sort()
print(list)
list.sort(reverse=True)
list.count("dhee")
print(list)
list.pop()
print(list)
list.insert(1,"halo")
print(list)
new=list.copy()
print(list)